name: Cross-Compile and Bundle Plugin

on:
  # Trigger when a tag is pushed for a release
  push:
    tags:
      - "*.*.*" # This will trigger when a tag like v1.0.0 is pushed
  # Manual trigger for creating an artifact (button in the UI)
  workflow_dispatch:

permissions:
  packages: write
  contents: write

jobs:
  build:
    name: Build and publish plugin release
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo for building
      - uses: actions/checkout@v4

      # Setup node for building
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      # Install the CLI tool for bundling
      - uses: taiki-e/install-action@v2
        with:
          tool: tilepad-cli

      # Build the plugin dependencies
      - name: Install dependencies
        run: npm install

      # Build the plugin
      - name: Run tilepad bundle
        run: npm run build

      # Bundle the plugin
      - name: Run tilepad bundle
        run: tilepad bundle --name plugin

      # Upload an artifact if manually triggered
      - name: Upload plugin artifact
        uses: actions/upload-artifact@v4
        if: github.event_name == 'workflow_dispatch'
        with:
          name: plugin.tilepadPlugin
          path: plugin.tilepadPlugin

      # Upload a release when a tag was created
      - name: Upload binary to release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push'
        with:
          draft: true
          files: plugin.tilepadPlugin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
